AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SuiseiCord_Discord_SAM

  SuiseiCord Main Discord Applications

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Parameters:
  ApplicationName:
    Description: ApplicationName.
    Type: String
  LoggingMode:
    Description: Logging Mode 'DEBUG' or 'INFO'.
    Type: String

Resources:
  SuiseiCordDiscordApplicationCommandsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: LambdaFunction/
      Handler: main.lambda_function
      Runtime: python3.9
      Policies:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
      Events:
        CallbackApi:
          Type: HttpApi # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /callback
            Method: POST
      Environment:
        Variables:
          APPLICATION_NAME: !Ref ApplicationName
          LOGGING_MODE: !Ref LoggingMode

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #CallbackAPIEndpoint:
    #Description: "API Gateway endpoint URL"
    #Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/callback"